# Generated by Django 4.2 on 2023-04-13 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('trible', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('religion', models.CharField(choices=[('empty', ''), ('christian', 'Christian'), ('islamic', 'Islamic'), ('other', 'Other')], default='empty', max_length=10)),
                ('blood_group', models.CharField(choices=[('empty', ''), ('group_A', 'Group A'), ('group_B', 'Group B'), ('group_AB', 'Group AB'), ('group_O', 'Group O')], default='empty', max_length=10)),
                ('gender', models.CharField(choices=[('empty', ''), ('male', 'Male'), ('female', 'Female')], default='empty', max_length=10)),
                ('region', models.CharField(max_length=50)),
                ('destrict', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_examination', models.CharField(max_length=500)),
                ('treatment_advice', models.TextField()),
                ('completed', models.BooleanField(choices=[(False, 'Pending'), (True, 'Done')], default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.patient')),
            ],
        ),
    ]
