# Generated by Django 4.2 on 2023-04-13 19:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personel',
            new_name='Personnel',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='trible',
            new_name='patient_id',
        ),
    ]
