# Generated by Django 4.2 on 2023-04-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_personel_personnel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='destrict',
            new_name='district',
        ),
    ]
