# Generated by Django 4.1.4 on 2023-02-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_request_request_date_alter_request_request_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='response_time',
        ),
    ]
