# Generated by Django 4.1.4 on 2023-02-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='comfidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.BooleanField(choices=[('New', False), ('Solved', True)]),
        ),
    ]
