# Generated by Django 4.2 on 2023-04-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_destrict_patient_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='treatment_advice',
            field=models.TextField(default=None),
        ),
    ]
