# Generated by Django 4.1.4 on 2023-02-13 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_accident_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.hospital'),
        ),
    ]
