# Generated by Django 4.1.4 on 2023-03-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_accident_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accident',
            old_name='comfidence',
            new_name='confidence',
        ),
    ]
