# Generated by Django 4.1.4 on 2023-03-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_nurse_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='response_date',
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='response_time',
            field=models.DateTimeField(default=None),
        ),
    ]
