# Generated by Django 4.1.4 on 2023-03-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_remove_attendence_date_alter_attendence_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='response_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
