# Generated by Django 4.1.4 on 2023-02-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='response_time',
            field=models.DateField(default=None),
        ),
    ]
