# Generated by Django 4.1.4 on 2023-03-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='informations',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
