# Generated by Django 4.1.4 on 2023-03-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='contacts',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_number',
            field=models.CharField(max_length=50),
        ),
    ]
