# Generated by Django 4.2 on 2023-04-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='details',
            field=models.CharField(choices=[('urination', 'Urination'), ('defecation', 'Defecation'), ('shower', 'Shower')], max_length=10),
        ),
    ]
