# Generated by Django 4.2 on 2023-04-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
