# Generated by Django 4.2 on 2023-07-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_informations_date_alter_informations_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Informations',
            new_name='Information',
        ),
    ]
