# Generated by Django 4.1.4 on 2023-02-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_request_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
