# Generated by Django 4.1.4 on 2023-02-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_accident_comfidence_alter_accident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='comfidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.BooleanField(),
        ),
    ]
