# Generated by Django 4.1.4 on 2023-03-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_device_contacts_alter_device_device_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='heat_rate',
            new_name='heart_rate',
        ),
    ]
