# Generated by Django 4.2 on 2023-04-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_transaction_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='details',
            field=models.TextField(),
        ),
    ]
