# Generated by Django 4.2 on 2023-04-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_report_latitude_report_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
