# Generated by Django 4.1.4 on 2023-02-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_request_request_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='request_time',
        ),
    ]
