# Generated by Django 4.2 on 2023-04-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_medical_treatment_advice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='treatment_advice',
            field=models.TextField(default='Error: Miss treatment advice from the Doctor'),
        ),
    ]
