# Generated by Django 4.1.4 on 2023-02-13 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_accident_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.hospital'),
        ),
    ]
