# Generated by Django 4.1.4 on 2023-03-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_accident_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.BooleanField(choices=[(False, 'New'), (True, 'Solved')], default=False),
        ),
    ]
