# Generated by Django 4.1.4 on 2023-02-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_request_request_date_request_request_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='response_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='request',
            name='response_time',
            field=models.TimeField(default=None),
        ),
    ]
