# Generated by Django 4.1.4 on 2023-02-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_delete_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('ward_name', models.CharField(max_length=100)),
                ('bed_number', models.PositiveIntegerField()),
            ],
        ),
    ]
