# Generated by Django 4.1.4 on 2023-02-27 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.device'),
        ),
    ]
