# Generated by Django 4.1.4 on 2023-02-28 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_weekday_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='day',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='nurse',
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.weekday'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='nurse',
            field=models.ManyToManyField(to='main_app.nurse'),
        ),
    ]
