# Generated by Django 4.1.4 on 2023-02-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_timetable_day_remove_timetable_nurse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='contacts',
            field=models.CharField(max_length=20),
        ),
    ]
