# Generated by Django 4.1.4 on 2023-03-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_request_request_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='date',
        ),
        migrations.AlterField(
            model_name='attendence',
            name='time_in',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
