# Generated by Django 4.1.4 on 2023-03-04 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0007_alter_accident_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flame', models.FloatField()),
                ('smoke', models.FloatField()),
                ('vibration', models.FloatField()),
                ('gyroscope', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('brake', models.BooleanField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vehicle')),
            ],
        ),
    ]
